version: "3.9"

services:
  app:
    container_name: homesupplies_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=homesupplies_db
      - POSTGRES_USER=homesupplies_user
      - POSTGRES_PASSWORD=homesupplies
      - POSTGRES_HOST=postgres-server

networks:
  default:
    external: true
    name: labens-network